### ISSUE TITLE
Energy conrtol

### ISSUE THREAD

**Issue by ghost** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1337] opened 2024-02-12 11:52 UTC
when I use energy control mod it crashes when I use thermometer and when I use cards

The game crashed whilst ticking block entity
Error: java.lang.NoClassDefFoundError: com/hbm/tileentity/machine/TileEntityMachineReactorLarge

**Comment by HbmMods** [comment] 2024-02-12 12:33
Duplicate of #1234, EC is not compatible with the current version of NTM, a fix is currently being worked on.

**Closed as completed by HbmMods** 2024-02-12 12:33 UTC
Labels: duplicate, mod conflict
