### ISSUE TITLE
Strontium uncastablility

### ISSUE THREAD

**Issue by Ilikepotatochips** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1741] opened 2024-10-19 22:07 UTC
In the latest release, 5091, Strontium-90 is uncastable despite having a smeltable form. This is very annoying when trying to automate rare-earth-ore bedrock ore. I understand this is to enable BSCCO but strontium should be castable to.

**Comment by R-Kaenbyou** [comment] 2024-10-20 23:35
Sodium and Neodymium have similar problem.

**Comment by HbmMods** [comment] 2024-10-23 07:37
Duplicate of #1572

**Closed as completed by HbmMods** 2024-10-23 07:37 UTC
