### ISSUE TITLE
Inconsistent glass interaction with new weapon mechanics

### ISSUE THREAD

**Issue by Wriar** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1816] opened 2024-12-19 04:48 UTC
**Issue**:
Guns in a previous version of the HBM mod used to be able to penetrate and break glass realistically. In the newly released version, shooting at glass with a gun no longer breaks it. This applies to ammunition that does not create a secondary explosion.

**Steps to Reproduce**:
1. Load a gun (Uzi, SPAS-12) with its accepted type of ammunition.
2. Place a block of glass.
3. Shoot at the aforementioned block of glass.
4. Witness that the glass doesn't break; recall that the glass should break when shot at in a previous mod version.

**Versioning Information:**
Mod Version: X5180
Forge Version: 1.7.10 10.13.4.1614

**Comment by HbmMods** [comment] 2024-12-19 06:49
Duplicate of #1813

**Closed as completed by HbmMods** 2024-12-19 06:49 UTC
