### ISSUE TITLE
 Artillery cannon mirv shells

### ISSUE THREAD

**Issue by Granniesgotaids** [HbmMods/Hbm-s-Nuclear-Tech-GIT#782] opened 2022-10-23 23:19 UTC
Artillery cannon shells that split isn't splitting at all. For example, the phosphorous 10x shell only drops one shell inaccurately. It's almost as if it is landing where it should in the circle but the other 9 are gone. The nuclear version does the same thing. I am using the latest version.

PS: allowing missile launch pads to work with artillery remotes would be lit

**Comment by HbmMods** [comment] 2022-11-03 10:19
Is it possible that while the shells do split, all submunitions are spawning with the same angle, making it look like there's only one? I know there used to be a similar issue with meteorites always spawning at the same angle and landing in the same place, I'm not sure what's causing that though. Perhaps another mod constantly resetting the RNG?

**Comment by HbmMods** [comment] 2022-11-07 14:48
As of X4410, multi shells now use an independent RNG which shouldn't be influenced by the world's RNG. Let me know if that fixed the issue.

**Comment by HbmMods** [comment] 2022-11-12 11:45
Just ran some tests, turns out it's actually the shells colliding with each other mid-air, causing all of them but one to explode. Confirmed to be fixed with the next release.

**Comment by Granniesgotaids** [comment] 2022-11-14 08:58
Hey thanks that fixed the issue.

**Closed as completed** 2022-11-14 08:58 UTC
Labels: bug, more info needed
