### ISSUE TITLE
The power switch cannot cut off power from the grid

### ISSUE THREAD

**Issue by sun00055555** [HbmMods/Hbm-s-Nuclear-Tech-GIT#593] opened 2022-04-30 06:35 UTC
After using the power switch block to cut off the grid, the machine at one end of the block still gets power from the other end.

Only return the game to the title interface and then enter the world can solve.

**Comment by sun00055555** [comment] 2022-04-30 06:41
It happened twice, once about 10 grids away and once more than 200 grids away.
All are not in the same block area

**Comment by HbmMods** [comment] 2022-04-30 09:07
Does the same thing happen when you break a cable block? You can find out whether cables are still connected by using the power network analysis tool. Could you also send me your mod list?

**Comment by sun00055555** [comment] 2022-04-30 09:29
![屏幕截图 2022-04-30 172727](https://user-images.githubusercontent.com/96975176/166100092-9e6017a0-63cf-4ae6-9618-f6b0efc85fda.png)

**Comment by sun00055555** [comment] 2022-04-30 09:29
I just tried to trigger it again, and it seems that this problem only arises when I enter a block of areas with a switch that has an on-state.
I used the grid to check the equipment and found that the grid was indeed disconnected, but the machine was still powered. When I exit re-entry, the power inside the machine is drained (I exit the world with the switch off), which causes it to look more like a transmission delay

**Comment by HbmMods** [comment] 2022-08-19 07:00
There was a confirmed bug that would cause grids to remain connected because of a fault in the system that does the required checks, should have been fixed in X4291. Marking this as closed, if it ever happens again please just reopen the issue.

**Closed as completed by HbmMods** 2022-08-19 07:00 UTC
Labels: more info needed
